# -*- coding: utf-8 -*-
"""Trabalho_pratico1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17tmtPslQRz6dUmGfeHuF2ro0B_Jvibwe
"""

#importando as bibliotecas
import pandas as pd
import plotly.express as px
import seaborn as sns
import numpy as np

custo_diario_base = pd.read_csv('custo_diaria.csv', sep=";")

custo_diario_base.describe()
custo_diario_base

custo_diario_x = custo_diario_base.iloc[:,0].values
custo_diario_y = custo_diario_base.iloc[:,1].values

np.corrcoef(custo_diario_x,custo_diario_y)

correlacao = custo_diario_base.corr()
plotar = sns.heatmap(correlacao, annot = True, linewidths = .3)
plotar

custo_diario_x.shape

custo_diario_x

custo_diario_x = custo_diario_x.reshape(-1,1)
custo_diario_x

custo_diario_x.shape

from sklearn.linear_model import LinearRegression
custo_diario_previsto = LinearRegression()

custo_diario_previsto.fit(custo_diario_x,custo_diario_y)

custo_diario_previsto.intercept_

custo_diario_previsto.coef_

previsao_precos_ = custo_diario_previsto.predict(custo_diario_x)
previsao_precos_

custo_diario_x
custo_diario_x.ravel()
custo_diario_y
custo_diario_y.ravel()

grafico=px.scatter(x=custo_diario_x.ravel(),y=custo_diario_y)
grafico.show()

grafico=px.scatter(x=custo_diario_x.ravel(),y=custo_diario_y)
  grafico.add_scatter(x=custo_diario_x.ravel(),y=previsao_precos_,name = 'previsao')
  grafico.show()

quantidade_pessoa= 17
custo_diario_previsto.intercept_ + custo_diario_previsto.coef_ * quantidade_pessoa

quantidade_pessoa= 25
custo_diario_previsto.intercept_ + custo_diario_previsto.coef_ * quantidade_pessoa

quantidade_pessoa= 27
custo_diario_previsto.intercept_ + custo_diario_previsto.coef_ * quantidade_pessoa

custo_diario_previsto.predict([[25]])

custo_diario_previsto.score(custo_diario_x, y=custo_diario_y)

from sklearn.metrics import mean_squared_error,mean_absolute_error
MSE = mean_squared_error(custo_diario_y,previsao_precos_)

MSE

mean_absolute_error(custo_diario_y,previsao_precos_)

np.sqrt(MSE)